spring:
    datasource:
        batch:
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
            jdbc-url: jdbc:sqlserver://localhost;databaseName=batch-meta;
            username: <username>
            password: <password>
        pay:
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
            jdbc-url: jdbc:sqlserver://localhost;databaseName=batch-test;
            username: <username>
            password: <password>
    batch:
        job:
            names: ${job.name:NONE}
    jpa:
        open-in-view: false
mybatis:
    mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
server:
    port: 8080
    servlet:
        context-path: /
logging:
    level:
        org.springframework.batch: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE
        org.hibernate.type.BasicTypeRegistry: WARN
